server:
  port: 8083

spring:

  #security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/microservices


  application:
    name: products-service

  cloud:
    config:
      enabled: false

  #Postgre
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Bilut2006b12
    url: jdbc:postgresql://localhost:5432/postgres

  #JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
      jakarta.persistence.validation.mode: none
    open-in-view: false

  #Redis
  data:
    redis:
      host: localhost
      port: 6379


  #Kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: products-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 10



#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}




